---

common:
  data_type : dirichlet_niid # data_type = data distribution one among ['iid','dirichlet_niid']
  dataset : SetFit/20_newsgroups # data_set = data set used one among ['SetFit/20_newsgroups', 'legacy-datasets/banking77', 'fancyzhx/dbpedia_14', 'cifar10', 'cifar100', 'mnist', 'fashion_mnist', 'sasha/dog-food', 'zh-plus/tiny-imagenet', 'Mike0307/MNIST-M', 'flwrlabs/usps']
  dirichlet_alpha : 0.01 #dirichlet concentration parameter (only used if data_type is dirchlet-niid)
  target_acc : 0.99
  # model : bert-base-uncased # one among [distilbert-base-uncased, bert-base-uncased, meta-llama/Llama-2-7b-hf, Net, CifarNet, SimpleCNN, KerasExpCNN, MNISTCNN, SimpleDNN, FMCNNModel,FedAVGCNN,Resnet18, Resnet34,ResNet18Pretrained, ResNet34Pretrained,ResNet18Small, ResNet20Small,MobileNetV2,EfficientNetB0,LSTMModel]
  model: distilbert-base-uncased
  # model: Qwen/Qwen1.5-0.5B
  optimizer : sgd # one among [sgd,adam]
  sgd_momentum : 0.9
  seed : 123  #123 456 789
  multi_node : False
  save_log : True
  num_train_thread: 1 #Save the most memory when setting to 1
  num_test_thread: 2

server:
  num_rounds : 10
  address : 127.0.0.1
  fraction_fit : 0.3 # fraction of clients to be selected for training
  min_fit_clients: 3 # minimum number of clients to be selected for training
  num_clients : 10 # total number of clients participating in training
  fraction_evaluate : 1 # fraction of clients to be selected for evaluation
  min_evaluate_clients: 10 # minimum number of clients to be selected for evaluation
  strategy : FedAvg #[FedAWA, FedKLSVD, FedAvg, FedLaw, FedProx, FedAvgM, FedOpt, FedAdam, FedMedian, PowD, Scaffold, FedNova]

client:
  loss: FocalLoss # [CrossEntropyLoss, FocalLoss]
  epochs : 1
  batch_size : 32
  test_batch_size : 32
  lr: 0.001 #  [0.00002, 0.0001,0.001, 0.005, 0.01, 0.1, 0.2] 0.005->distilbert-base-uncased, 0.001->bert-base-uncased, 0.0001->Qwen/Qwen1.5-0.5B
  save_train_res : True
  total_cpus : 36 # no. of CPU cores that are assigned for all simulation
  total_gpus : 1 # no. of GPU's assigned for whole simulation
  gpu : True  # True or False, Use GPU for training or not.
  num_cpus : 2  # no. of CPU cores that are assigned for each actor
  num_gpus : 0.05 #  no. of GPU that are assigned for each actor (it can be fraction value as well)

peft:
  enabled: True  #False = FFT, do not set method = fedkls when running FFT
  rank: 32
  alpha: 32 #Equal to the rank
  method: lora # ['pissa', 'milora', 'middle', 'fedkls', 'lora']

fedawa_config:
  server_valid_ratio: 0.02 
  server_epochs: 10       
  server_optimizer: adam   
  server_lr: 0.01
  gamma: 1.0            
  reg_distance: cos       

fedlaw_config:
  server_funct : 'exp' #['exp' or 'quad'] #currently exp only is implemented
  server_optimizer : 'adam'
  server_valid_ratio : 0.02 #percentage of data used for server side retraining
  server_epochs : 10

fedprox:
  proximal_mu : 0.01

powd_config:
  candidate_client_set: 20 # the d parameter (client fraction ≤ d ≤ total clients)
