---
# config

common:
  data_type : iid #data_type = data distribution one among ['iid','dirichlet-niid']
  dataset : mnist #data_set = data set used  one among [fashionmnist,mnist,cifar10 ]
  dirichlet_alpha : 0.11 #dirichlet concentration parameter (only used if data_type is dirchlet-niid)
  target_acc : 0.95
  model : resnet18 #one among [resnet18]
  optimizer : sgd # one among [sgd,adam]
  seed : 133

server:
  num_rounds : 21
  address : 127.0.0.1
  fraction_fit : 0.05
  min_fit_clients: 2
  num_clients : 20  # total number of clients participating in training 
  fraction_evaluate : 0.025
  strategy : fedavg #Strategy : choices=['fedavg', 'fedyogi', 'fedadagrad', 'fedavgm','fedprox']

client:
  epochs : 2
  batch_size : 64
  lr: 0.001  #[0.0001,0.001,0.005,0.01,0.1,0.2]
  save_train_res : True
  total_cpus : 20
  total_gpus : 1
  gpu : true  # True or False, Use GPU for training or not.
  num_cpus : 2  # no. of CPU cores that are assigned for each actor
  num_gpus : 0.0  # no. of GPU that are assigned for each actor (it can be fraction value as well)




