site_name: FedEasy
site_url: !ENV READTHEDOCS_CANONICAL_URL

theme:
  name: readthedocs
  display_version: True
  highlightjs: True
  hljs_languages:
    - yaml
    - bash

nav:
  - Installaton & Setup: install.md
  - Configuration: config.md
  - Datasets: datasets.md
  - Data Distributions: data_distribution.md
  - Models : models.md
  - Strategies: strategies.md
  - Contributing: contributing.md
  - License: license.md

